version: "3.8"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: chessApp
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: dungb
      MYSQL_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306" # Map container port 3306 to host port 3306
